### ISSUE TITLE
getkey is incompatible with PEP 517

### ISSUE THREAD

**Issue by betterthanever2** [mimseyedi/pysentation#2]
I'm trying to install `pysentation`, but can't because one of the primary dependencies, `getkey` (v. 0.6.5, last updated in 2016), does not support PEP 517 builds.

My project is poetry-based, but with plain `pip` it fails just the same.

Here's the full output I'm getting:

```
(wapatools-py3.11) PS D:\code\wapatools_main> poetry add pysentation
Using version ^1.0.0 for pysentation

Updating dependencies
Resolving dependencies...

Package operations: 5 installs, 1 update, 0 removals

  • Installing mdurl (0.1.2)
  • Installing markdown-it-py (2.2.0)
  • Updating click (8.1.7 -> 8.1.3)
  • Installing getkey (0.6.5)
  • Installing rich (13.4.1)

  ChefBuildError

  Backend subprocess exited when trying to invoke get_requires_for_build_wheel

  Traceback (most recent call last):
    File "C:\Users\user\AppData\Roaming\pypoetry\venv\Lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "C:\Users\user\AppData\Roaming\pypoetry\venv\Lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\user\AppData\Roaming\pypoetry\venv\Lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
             ^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\user\AppData\Local\Temp\tmp5toy3h9y\.venv\Lib\site-packages\setuptools\build_meta.py", line 355, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\user\AppData\Local\Temp\tmp5toy3h9y\.venv\Lib\site-packages\setuptools\build_meta.py", line 325, in _get_build_requires
      self.run_setup()
    File "C:\Users\user\AppData\Local\Temp\tmp5toy3h9y\.venv\Lib\site-packages\setuptools\build_meta.py", line 507, in run_setup
      super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
    File "C:\Users\user\AppData\Local\Temp\tmp5toy3h9y\.venv\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
      exec(code, locals())
    File "<string>", line 37, in <module>
    File "<string>", line 11, in read_description
    File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 23, in decode
      return codecs.charmap_decode(input,self.errors,decoding_table)[0]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 876: character maps to <undefined>


  at ~\AppData\Roaming\pypoetry\venv\Lib\site-packages\poetry\installation\chef.py:147 in _prepare
      143│
      144│                 error = ChefBuildError("\n\n".join(message_parts))
      145│
      146│             if error is not None:
    → 147│                 raise error from None
      148│
      149│             return path
      150│
      151│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with getkey (0.6.5) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "getkey (==0.6.5)"'.      
```

**Comment by mimseyedi** [comment]
I have not encountered this error before and this is the first time I see something like this. The getkey package is a free and small package that I used in this project to control input keys. Maybe I should use another package for this (also this package is not well adapted to Windows!), but until then I hope this [link](https://stackoverflow.com/questions/64038673/could-not-build-wheels-for-which-use-pep-517-and-cannot-be-installed-directly) can help you.

Also, if I'm not mistaken, the error message suggested this solution:
```
pip wheel --use-pep517 "getkey (==0.6.5)"
```
